### ISSUE TITLE
Code demo for web chat feature

### ISSUE THREAD

**Issue by longlh** [ntq-lab/easy-chat#1]
Create a demo for chat one-to-one feature
- [x] Read book Node in Action
- [x] Following web chat example in the book (chat room, many-to-many chat)
- [x] Improve the example for one-to-one chat
- [x] Demo to team

**Comment by hoangnv552** [comment]
Hi anh Long,
Plan đọc sách làm ví dụ này là bọn em tự control  ạ?

**Comment by longlh** [comment]
@hoangnv552, @vuongtaquoc, @vanthaophamit: cuối tuần này demo vụ này nhé

**Comment by hoangnv552** [comment]
Hi anh Long,

Thứ 7 này em xin nghỉ nhé, em về đám cưới chị ạ.

On Thu, Mar 5, 2015 at 10:48 AM, Luc Hoang Long notifications@github.com
wrote:

> @hoangnv552 https://github.com/hoangnv552, @vuongtaquoc
> https://github.com/vuongtaquoc, @vanthaophamit
> https://github.com/vanthaophamit: cuối tuần này demo vụ này nhé
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ntq-lab/easy-chat/issues/1#issuecomment-77301642.

## 

_Nông Văn Hoàng_
