### ISSUE TITLE
Study / Implement Gruntfile

### ISSUE THREAD

**Issue by longlh** [ntq-lab/easy-chat#3]
Study then try to implement Grunt for new project.
- [x] Study Grunt
  - [x] Read document on http://gruntjs.com/
  - [x] Clone and run repo https://github.com/ntq-lab/ntq-website-v2
  - [x] Study Gruntfile.js in this repo
  - [x] Understand using Grunt
- [x] Implement Grunt
  - [x] jscs
  - [x] csslint
  - [x] jshint
  - [x] cssmin
  - [x] uglify
  - [x] filerev
  - [x] watch
- [x] Study NGINX (optional)
- [x] Create document about build flow

**Comment by longlh** [comment]
@truongnguyen1912 em follow cùng để đưa ra đc khung áp dụng Grunt cho các dự án PHP

**Comment by longlh** [comment]
@hoangnv552 em bố trí tìm hiểu task này trước nhé

**Comment by longlh** [comment]
@hoangnv552 anh thêm 1 task về việc tạo document cho build flow nhé. Làm nốt task này em có thể close issue này.

**Comment by hoangnv552** [comment]
Vâng ạ
